// <auto-generated />
namespace PDS2_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class compra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(compra));
        
        string IMigrationMetadata.Id
        {
            get { return "202011181050586_compra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
